VinVC/VinVC/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('login.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^', include('video_room.urls')),

    url(r'^admin/', admin.site.urls),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VinVC/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^(?P<user_id>[0-9]+)/friends/$', views.friends, name='friends'),
    url(r'^(?P<user_id>[0-9]+)/uploaded/$', views.uploaded, name='uploaded'),
    url(r'^(?P<user_id>[0-9]+)/watched/$', views.watched, name='watched'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^requests/$', views.requests, name='requests'),
]

VinVC/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

def avatar_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/avatars/<username>.jpg
    return 'avatars/{}.jpg'.format(instance.username)

class CustomUser(AbstractUser):
    """
    A custom user model with unique email field
    """
    email = models.EmailField(max_length=40, unique=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    avatar = models.ImageField(upload_to=avatar_directory_path,
                               default='avatars/placeholder.jpg')

    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

VinVC/video/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from .validators import validate_file_extension


class Video(models.Model):
    title = models.CharField(blank=True, max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='author')
    date_upload = models.DateTimeField('date upload', default=timezone.now)
    video_file = models.FileField(upload_to="videos/%Y/%m/%d",
                                  validators=[validate_file_extension])
    thumbnail = models.ImageField(upload_to="videos/%Y/%m/%d", blank=True)
    description = models.CharField(blank=True, max_length=200, default="")
    views = models.IntegerField(default=0)
    watchers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      through='WatchedUsers',
                                      through_fields=('video', 'user'),
                                      symmetrical=True)

    def update_views(self):
        self.views += 1
        self.save()

    def __str__(self):
        return "Title: {}, Description: {}, Author: {}, Date: {}, File: {}, " \
               "Thumbnail: {}, Views: {}, Watchers: {}".\
            format(self.title, self.description, self.author, self.date_upload,
                   self.video_file.name, self.thumbnail, self.views,
                   self.watchers.all())


class WatchedUsers(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='user_watch')
    video = models.ForeignKey(Video, on_delete=models.CASCADE,
                              related_name='video_watch')
    date = models.DateTimeField('date view', default=timezone.now)

    def __str__(self):
        return "User: {}, Video: <<{}>>, Date: {}".format(self.user,
                                                          self.video,
                                                          self.date)

VinVC/user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from .models import CustomUser

class UpdateUserForm(forms.ModelForm):
    old_password = forms.CharField(widget=forms.PasswordInput(
                                   attrs={'placeholder': 'Old password'}))
    new_password = forms.CharField(widget=forms.PasswordInput(
                                   attrs={'placeholder': 'New password'}),
                                   required=False)
    retry_password = forms.CharField(widget=forms.PasswordInput(
                                     attrs={'placeholder': 'Retry new password'}),
                                     required=False)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'avatar']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last name'}),
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
        }

    def clean_old_password(self):
        password = self.cleaned_data.get('old_password', None)
        if not self.instance.check_password(password):
            raise ValidationError('Invalid password')

    def clean_retry_password(self):
        new = self.cleaned_data.get('new_password', None)
        retry = self.cleaned_data.get('retry_password', None)
        if new and new != retry:
            raise ValidationError('Password not match')

VinVC/user/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth import update_session_auth_hash

from video.models import Video, WatchedUsers
from .forms import UpdateUserForm


@login_required
def profile(request, user_id):
    my_friendship = request.user.friendship
    profile = get_object_or_404(get_user_model(), pk=user_id)
    status = 'same_user'
    request_id = None

    if profile != request.user:
        status = my_friendship.get_friendship_status(profile)
        if status == 'need_response':
            request_id = my_friendship.get_pending_requests(
                from_user=profile.friendship)[0].id

    context = {'profile': profile,
               'status': status,
               'request_id': request_id}

    return render(request, 'user/profile.html', context)


@login_required
def requests(request):
    full = request.GET.get('full', "true")
    if full == 'false':
        friendship_requests_list = request.user.friendship.get_pending_requests()
        context = {'profile': request.user,
                   'friendship_requests_list': friendship_requests_list}
        return render(request, 'user/requests.html', context)
    else:
        return redirect('{}#requests'.format(reverse('user:profile',
                        kwargs={'user_id': request.user.id})))


@login_required
def friends(request, user_id):
    full = request.GET.get('full', "true")
    user = get_object_or_404(get_user_model(), id=user_id)
    if full == 'false':
        friendship_list = user.friendship.friends.all()
        context = {'profile': request.user, 'friendship_list': friendship_list}
        return render(request, 'user/friends.html', context)
    else:
        return redirect('{}#friends'.format(reverse('user:profile',
                        kwargs={'user_id': user.id})))


@login_required
def uploaded(request, user_id):
    full = request.GET.get('full', "true")
    user = get_object_or_404(get_user_model(), id=user_id)
    if full == 'false':
        videos = Video.objects.filter(author=user)
        context = {'show_delete': request.user == user, 'video_list': videos}
        return render(request, "user/uploaded.html", context)
    else:
        return redirect('{}#uploaded'.format(reverse('user:profile',
                        kwargs={'user_id': user.id})))


@login_required
def watched(request, user_id):
    full = request.GET.get('full', "true")
    user = get_object_or_404(get_user_model(), id=user_id)
    if full == 'false':
        watched_videos = WatchedUsers.objects.filter(user=user).values('video')
        videos = Video.objects.filter(pk__in=watched_videos)
        context = {'profile': user, 'video_list': videos}
        return render(request, "user/watched.html", context)
    else:
        return redirect('{}#watched'.format(reverse('user:profile',
                        kwargs={'user_id': user.id})))


@login_required
def edit(request):
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            new_user = form.save(commit=False)

            if form.cleaned_data['new_password']:
                new_user.set_password(form.cleaned_data['new_password'])
                update_session_auth_hash(request, new_user)

            new_user.save()
            form.save_m2m()
            return redirect(reverse('user:profile',
                                    kwargs={'user_id': request.user.id}))
    else:
        form = UpdateUserForm(initial={'password' : ''}, instance=request.user)
    return render(request, 'user/edit.html', {'form': form})

VinVC/user/templates/user/edit.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <title>Edit profile</title>
    <link rel='stylesheet' href="{% static 'user/css/user.css' %}" />
{% endblock %}

{% block content %}
    <legend>Edit your profile</legend>

    <div class="container-fluid">
        <div class="col-sm-3 col-md-6 col-lg-4">
            <div id="user-edit-profile-image">
                <img class="img-circle" src="{{ user.avatar.url }}" />
            </div>
        </div>

        <div class="col-sm-9 col-md-6 col-lg-8">
            <form action="{% url 'user:edit' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include "form.html" with form=form only %}
                <input class="btn site-button" type="submit" value="Save"/>
            </form>
        </div>
    </div>
{% endblock %}

VinVC/user/templates/user/friends.html
<div id="grid-container">

    {% for friend in friendship_list %}
        {% include "preview_user.html" with preview_user=friend.user only %}
    {% empty %}
        <p>Nothing here...</p>
    {% endfor %}

</div>

VinVC/user/templates/user/profile.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  {% block profile %}
  {% endblock %}
  <title>{{ user.get_full_name }}'s Profile</title>
  <link rel='stylesheet' href="{% static 'user/css/user.css' %}" />
{% endblock %}

{% block content %}
    <div id="profile-header-container">
        <div id="profile-header">
            <div id="profile-header-image-container">
                <div id="profile-header-image">
                    <img class="img-circle" src="{{ profile.avatar.url }}" />
                </div>
                <span>{{ profile.get_full_name }}</span>
            </div>
            <div id="profile-header-info-container">
                <p id="member-status">Member since<br/><span>{{ profile.date_joined|date:"d M Y" }}</span></p>
                <span>
                    <span class="value">{{ profile.friendship.get_friends.count }}</span>
                    <span class="text">Friends</span>
                </span>
                <span>
                    <span class="value">{{ profile.video_set.all.count }}</span>
                    <span class="text">Videos</span>
                </span>
                <p id="user-status">
                    {% if status == 'friends' %}
                        You are already friends
                    {% elif status == 'already_sent_request' %}
                        Request pending
                    {% elif status == 'allow_send_request' %}
                        <a class="btn site-blue-button" href="#" onclick="sendRequest({{ profile.id }});updateStatus(this, 'sent');">Send request</a>
                    {% elif status == 'need_response' %}
                        <a class="btn site-blue-button" href="#" onclick="acceptRequest({{ request_id }});updateStatus(this, 'accepted');">Accept</a>
                        <a class="btn site-white-button" href="#" onclick="rejectRequest({{ request_id }});updateStatus(this, 'rejected')">Reject</a>
                    {% elif status == 'same_user' %}
                        <a class="btn site-blue-button" href="{% url 'user:edit' %}">Edit</a>
                    {% endif %}
                </p>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <nav id="menu">
        <ul class="menu">
            {% if status == 'same_user' %}
                <li><a id="watched" href=#>
                    <span>Watched Videos</span>
                </a></li>
                <li><a id="uploaded" href=#>
                    <span>Uploaded Videos</span>
                </a></li>
                <li><a id="requests" href=#>
                    <span>Friendship Request</span>
                </a></li>
                <li><a id="friends" href=#>
                    <span>Friends</span>
                </a></li>
            {% elif status == 'friends' %}
                <li><a id="watched" href=#>
                    <span>Watched Videos</span>
                </a></li>
                <li><a id="uploaded" href=#>
                    <span>Uploaded Videos</span>
                </a></li>
                <li><a id="friends" href=#>
                    <span>Friends</span>
                </a></li>
            {% else %}
                <li><a id="uploaded" href=#>
                    <span>Uploaded Videos</span>
                </a></li>
                <li><a id="friends" href=#>
                    <span>Friends</span>
                </a></li>
            {% endif %}
        </ul>
    </nav>

    <script>
        $(document).ready(function(){
            $('#friends').click(function() {
                addActive(this);
                $.get("{% url 'user:friends' profile.id %}?full=false", toggleContent);
                return false;
            });
            $('#uploaded').click(function() {
                addActive(this);
                $.get("{% url 'user:uploaded' profile.id %}?full=false", toggleContent);
                return false;
            });
            $('#watched').click(function() {
                addActive(this);
                $.get("{% url 'user:watched' profile.id %}?full=false", toggleContent);
                return false;
            });
            $('#requests').click(function() {
                addActive(this);
                $.get("{% url 'user:requests' %}?full=false", toggleContent);
                return false;
            });

            function toggleContent(html) {
                $("#profile-content").fadeOut(300, function() {
                    $("#profile-content").empty().append(html);
                    $("#profile-content").fadeIn(200);
                });
            }

            function addActive(elem) {
                $(elem).parent().parent().children().each(function() {
                    $(this).removeClass('active');
                });
                $(elem).parent().addClass('active');
            }

            if (window.location.hash) {
                $(window.location.hash).click();
            } else {
                $("#uploaded").click();
            }
      });

    </script>

    <div id="profile-content">
    </div>

    <script>
    function updateStatus(elem, status) {
        if (status == 'sent')
            $(elem).parent().html("Request Pending");
        else if (status == 'accepted')
            $(elem).parent().html("You are already friends");
        else if (status == 'rejected')
            $(elem).parent().html("<a class='btn site-blue-button' href='#' onclick=\"sendRequest({{ profile.id }});updateStatus(this, 'sent');\">Send request</a>");
    }
    </script>
{% endblock %}

VinVC/user/templates/user/requests.html
<div id="grid-container">

    <div class="row">
        {% for request in friendship_requests_list %}
            {% include "preview_user.html" with preview_user=request.sender.user preview_request=request only %}
        {% empty %}
            <p>You don't have any Friendship Request.</p>
        {% endfor %}
    </div>

</div>

VinVC/user/templates/user/uploaded.html
<div id="grid-container">

    {% for video in video_list %}
        {% include "preview_video.html" with preview_video=video preview_delete=show_delete only %}
    {% empty %}
        <p>Nothing here...</p>
    {% endfor %}

</div>

VinVC/user/templates/user/watched.html
<div id="grid-container">

    {% for video in video_list %}
        {% include "preview_video.html" with preview_video=video only %}
    {% empty %}
        <p>Nothing here...</p>
    {% endfor %}

</div>