VinVC/VinVC/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('login.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^', include('video_room.urls')),

    url(r'^admin/', admin.site.urls),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VinVC/login/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
]

VinVC/search/urls.py
from django.conf.urls import url

from . import views

app_name = 'search'
urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^api/$', views.api, name='api'),
]

VinVC/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^(?P<user_id>[0-9]+)/friends/$', views.friends, name='friends'),
    url(r'^(?P<user_id>[0-9]+)/uploaded/$', views.uploaded, name='uploaded'),
    url(r'^(?P<user_id>[0-9]+)/watched/$', views.watched, name='watched'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^requests/$', views.requests, name='requests'),
]

VinVC/video/urls.py
from django.conf.urls import url
from . import views

app_name = 'video'
urlpatterns = [
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^delete/$', views.delete, name='delete'),
]

VinVC/video_room/urls.py
from django.conf.urls import url
from . import views

app_name = 'video_room'
urlpatterns = [
    url(r'^feed/$', views.feed, name='feed'),
    url(r'^room/(?P<label>[\w-]{,50})/$', views.join, name='join'),
    url(r'^room/new/(?P<video_id>[0-9]+)/$', views.new, name='new'),
]

VinVC/VinVC/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />

        <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <script src="{% static 'js/csrf_ajax.js' %}"></script>
        {% block head %}{% endblock %}
    </head>
    <body>

    {% if user and user.is_authenticated %}
        {# Top bar #}
        <div id="header-container" class="clearfix">
            <div id="header">
                <a href="/" id="header-logo"></a>
                <div id="header-user">
                    <a href="{% url 'video:upload' %}" id="header-upload" class="btn site-button">Upload</a>
                    <div id="notification-container" class="dropdown">
                        <button id="header-notification-bell" class="dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="notification-count">0</span>
                        </button>
                        <ul id="notification-list" class="dropdown-menu pull-right" role="menu" aria-labelledby="header-notification-bell">
                            <li><a role="menuitem" tabindex="-1" href="#">No notifications</a></li>
                        </ul>
                    </div>
                    <div id="header-account-container" class="dropdown">
                        <button id="header-account" title="{{ user.first_name }} {{ user.last_name }}" class="dropdown-toggle" type="button" data-toggle="dropdown">
                            <img id="user-profile-image" class="img-circle" src="{{ user.avatar.url }}" />
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="header-account">
                            <li><a role="menuitem" tabindex="-1" href="{% url 'user:profile' user.id %}">My Profile</a></li>
                            <li><a role="menuitem" tabindex="-1" href="{% url 'user:friends' user.id %}">My Friends</a></li>
                            <li class="divider"></li>
                            <li><a role="menuitem" tabindex="-1" href="{% url 'login:logout' %}">Log out</a></li>
                        </ul>
                    </div>
                </div>
                <div id="header-search-bar">
                    <form action="{% url 'search:search' %}">
                        <button id="search-button"><i class="fa fa-search" aria-hidden="true"></i></button>
                        <div id="header-search-term-container">
                            <input name="key" id="header-search-term" autocomplete="off" autofocus="" required value="" type="text" tabindex="1" placeholder="Search..." title="Search..." aria-label="Search..." dir="ltr" spellcheck="false" style="outline: none;">
                        </div>
                    </form>
                </div>
                <div id="results-container">
                    <ul id="search-list" class="ui-front">
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}

    <div id="content-wrapper">
        {% block content %}
        {% endblock %}
    </div>

    {% if user and user.is_authenticated %}
        <script language="JavaScript">
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var friendship_socket = new WebSocket(ws_scheme + '://' + window.location.host + "/friendship/");

            var notification_count = $(".notification-count");

            function getUserProfile(id) {
                var user_profile_url = "{% url 'user:profile' 0 %}";
                return user_profile_url.replace(/0/, id.toString());
            }

            friendship_socket.onmessage = function(message) {
                var data = JSON.parse(message.data);

                if (data.length > 0) {
                    if (!$("#header-notification-bell").hasClass('active')) {
                        $("#header-notification-bell").addClass('active');
                        $("#notification-list").empty();
                    }

                    notification_count.text(parseInt(notification_count.text()) + data.length);

                    for (var i in data) {
                        $("#notification-list").prepend(
                                "<li class='notification'>"
                                    + "<a href='"+ getUserProfile(data[i].user_id) +"'>" + data[i].user+ "</a>"
                                    + "<button class='btn site-blue-button' onclick='remove(this);acceptRequest(" + data[i].id +")'>Accept</button>"
                                    + "<button class='btn site-white-button' onclick='remove(this);rejectRequest(" + data[i].id +")'>Reject</button>"
                                + "</li>"
                        );
                    }
                }
            };

            function remove(link) {
                link.parentNode.parentNode.removeChild(link.parentNode);
            }

            function decrementNotificationCount() {
                if (notification_count.text() > 0)
                    notification_count.text(parseInt(notification_count.text()) - 1);

                if (notification_count.text() === '0') {
                    if ($("#header-notification-bell").hasClass('active')) {
                        $("#header-notification-bell").removeClass('active');
                        $("#notification-list").append(
                                "<li><a role='menuitem' tabindex='-1' href='#'>No notifications</a></li>"
                        );
                    }
                }
            }

            function acceptRequest(id) {
                var message = {
                    method: 'accept',
                    id: id
                };
                friendship_socket.send(JSON.stringify(message));
                decrementNotificationCount();
            }

            function rejectRequest(id) {
                 var message = {
                    method: 'reject',
                    id: id
                };
                friendship_socket.send(JSON.stringify(message));
                decrementNotificationCount();
            }

            function sendRequest(id) {
                var message = {
                    method: 'send',
                    id: id
                };
                friendship_socket.send(JSON.stringify(message));
            }
        </script>
    {% endif %}
    </body>
</html>

VinVC/VinVC/templates/form.html
{% for field in form %}
    <div class="form-field">
        {% for error in field.errors %}
            <p class="error-message">{{ error }}</p>
        {% endfor %}

        {{ field }}

    </div>
{% endfor %}

VinVC/VinVC/templates/preview_user.html
{% load static %}

{% comment %}
    use with
    preview_user: a user to display preview
    preview_request: if present, append request to user preview
{% endcomment %}

<div class="col-xs-11 col-sm-4 col-md-2 col-lg-2 grid-item-container">
    <div class="user-profile-header">
    </div>
    <div class="user-profile-image">
        <a href="{% url 'user:profile' preview_user.id %}">
            <img class="img-circle" src="{{ preview_user.avatar.url }}" />
        </a>
    </div>
    <div class="grid-holder">
        <span class="user-profile-name">
            <a href="{% url 'user:profile' preview_user.id %}">
                {{ preview_user.get_full_name }}
            </a>
        </span>
        {% if preview_request %}
            <span class="user-profile-date">
                {{ preview_request.sent_date|date:"M d, Y f" }}
            </span>
            <span>
                <button class="btn site-blue-button" href=# onclick='acceptRequest({{ preview_request.id }})'>Accept</a>
                <button class="btn site-white-button" href=# onclick='rejectRequest({{ preview_request.id }})'>Reject</a>
            </span>
        {% endif %}
    </div>
</div>

VinVC/VinVC/templates/preview_video.html
{% comment %}
    Usage with
    preview_video: video to display preview
    preview_user: if present, show user on top of thumbnail and link to VideoRoom
    preview_delete: if equal to True, show delete button
{% endcomment %}

<div class="col-xs-11 col-sm-4 col-md-2 col-lg-1 grid-item-container">
    {% if preview_user %}
        <div class="grid-head">
            <a href="{% url 'user:profile' preview_user.user.id %}">
                <span class="user-profile-image-mini">
                    <img class="img-circle" src="{{ preview_user.user.avatar.url }}" />
                </span>
                <span class="user-profile-name">
                    {{ preview_user.user.get_full_name }}
                </span>
            </a>
        </div>
        <a href="{% url 'video_room:join' preview_user.room.label %}">
    {% else %}
        <a href="{% url 'video_room:new' preview_video.pk %}">
    {% endif %}
        <div class="video-thumbnail">
            <img src="{{ preview_video.thumbnail.url }}" />
        </div>
    </a>
    <div class="grid-holder">
        <span class="video-name">
            {% if preview_user %}
                <a href="{% url 'video_room:join' preview_user.room.label %}">
            {% else %}
                <a href="{% url 'video_room:new' preview_video.pk %}">
            {% endif %}
                {{ preview_video.title }}
            </a>
        </span>
        <span class="video-description">
            {{ preview_video.description }}
        </span>
        {% if preview_delete is True %}
            <a class="btn btn-delete" href="{% url 'video:delete' %}?id={{ preview_video.id }}">
                <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
            </a>
        {% endif %}
    </div>
</div>