VinVC/VinVC/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('login.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^', include('video_room.urls')),

    url(r'^admin/', admin.site.urls),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VinVC/search/urls.py
from django.conf.urls import url

from . import views

app_name = 'search'
urlpatterns = [
    url(r'^$', views.search, name='search'),
    url(r'^api/$', views.api, name='api'),
]

VinVC/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^(?P<user_id>[0-9]+)/friends/$', views.friends, name='friends'),
    url(r'^(?P<user_id>[0-9]+)/uploaded/$', views.uploaded, name='uploaded'),
    url(r'^(?P<user_id>[0-9]+)/watched/$', views.watched, name='watched'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^requests/$', views.requests, name='requests'),
]

VinVC/video_room/urls.py
from django.conf.urls import url
from . import views

app_name = 'video_room'
urlpatterns = [
    url(r'^feed/$', views.feed, name='feed'),
    url(r'^room/(?P<label>[\w-]{,50})/$', views.join, name='join'),
    url(r'^room/new/(?P<video_id>[0-9]+)/$', views.new, name='new'),
]

VinVC/video_room/models.py
from django.db import models
from video.models import Video
from django.utils import timezone
from django.conf import settings


class VideoRoom(models.Model):
    label = models.SlugField(unique=True, null=True)
    paused = models.BooleanField(default=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    started_playing = models.DateTimeField('started playing', default=timezone.now)
    current_time = models.FloatField(default=0.0)

    def __str__(self):
        return "Video: {}, Paused: {}".format(self.video, self.paused)


class VideoRoomUsers(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='user')
    room = models.ForeignKey(VideoRoom, on_delete=models.CASCADE,
                              related_name='room')
    date = models.DateTimeField('date view', default=timezone.now)

    def __str__(self):
        return "User: {}, Room: <<{}>>, Date: {}".format(self.user,
                                                          self.room,
                                                          self.date)

VinVC/video_room/views.py
import random
from hashlib import sha1

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.db import transaction

from .models import VideoRoom, VideoRoomUsers
from video.models import Video, WatchedUsers


@login_required
def feed(request):
    friendship_list = request.user.friendship.get_friends()
    friends = VideoRoomUsers.objects.filter(user__friendship__in=friendship_list)
    most_viewed = Video.objects.order_by('-views')[:10]
    context = {'friend_watching': friends,
               'most_viewed': most_viewed}
    return render(request, "video_room/feed.html", context)


@login_required
def join(request, label):
    room = get_object_or_404(VideoRoom, label=label)

    _, created = WatchedUsers.objects.update_or_create(user=request.user,
                                                       video=room.video)

    if created:
        room.video.update_views()

    video_list = Video.objects.all().exclude(id=room.video.id)

    context = {'room': room, 'video_list': video_list}
    return render(request, "video_room/player.html", context)


def random_label():
    while True:
        with transaction.atomic():
            label = sha1(str(random.getrandbits(256)).encode('utf-8')).hexdigest()
            if not VideoRoom.objects.filter(label=label).exists():
                break
    return label

@login_required
def new(request, video_id):
    """
    Randomly create a new room, and redirect to it.
    """
    video = get_object_or_404(Video, id=video_id)
    new_room = VideoRoom.objects.create(video=video, label=random_label())
    return redirect(reverse('video_room:join', kwargs={'label': new_room.label}))

VinVC/video_room/templates/video_room/feed.html
{% extends "base.html" %}

{% block head %}
    <title>Videos</title>
{% endblock %}

{% block content %}

    <h1> Friends are watching.</h1>
    {% for friend in friend_watching %}
        {% include "preview_video.html" with preview_video=friend.room.video preview_user=friend only %}
    {% empty %}
        <p>Nothing here...</p>
    {% endfor %}

    <h1> Most viewed. </h1>
    {% for video in most_viewed %}
        {% include "preview_video.html" with preview_video=video only %}
    {% empty %}
        <p>Nothing here...</p>
    {% endfor %}

{% endblock %}

VinVC/video_room/templates/video_room/player.html
{% extends "base.html" %}
{% load static chat_room_tags %}

{% block head %}
    <title>Videos</title>
    <link rel='stylesheet' href="{% static 'video_room/css/player.css' %}" />
    <link href="http://vjs.zencdn.net/5.8.8/video-js.min.css" rel="stylesheet">

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
    </script> <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

    {% chat_room_headers %}
{% endblock %}

{% block content %}
    <h3><strong> {{ room.video.title }} </strong></h3>
    <div id="player-container">
        <div id="video-container">
            <video id="player" class="video-js" controls preload="auto" data-setup="{}">
                <source src="{{ room.video.video_file.url }}">
                Your browser does not support HTML5 video.
            </video>
            {% if room.video.description %}
                <blockquote> {{ room.video.description }} </blockquote>
            {% endif %}
        </div>
        <div id="chat-room-container">
            {% show_chat_room room.id %}
        </div>
    </div>
    <script src="http://vjs.zencdn.net/5.8.8/video.min.js"></script>
    <script>
        var video_room_id = {{ room.id }};

        // When we're using HTTPS, use WSS too.
        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";

        var locked = false;

        videojs("player").ready(function () {
            //noinspection JSUnusedAssignment
            var video_room_socket = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + "/video_room/" + video_room_id);
            var player = document.getElementById("player_html5_api");

            player.addEventListener('loadeddata', function() {
                video_room_socket.onmessage = function(message) {
                    var data = JSON.parse(message.data);

                    locked = true;
                    console.log(data);
                    if (data.method == "update") {
                        if (Math.abs(player.currentTime - data.current_time) > 0.2)
                            player.currentTime = data.current_time;
                        if (data.paused == true && !player.paused)
                            player.pause();
                        else if (data.paused == false && player.paused)
                            player.play();
                        else
                            locked = false;
                    } else if (data.method == "change") {
                        video_room_socket.close();
                        window.location.replace(window.location.href);
                    }

                };

                video_room_socket.onopen = function() {
                    console.log("Sending force update");
                    var message = {
                        method: "force"
                    };
                    video_room_socket.send(JSON.stringify(message));
                }

                if (video_room_socket.readyState == WebSocket.OPEN) video_room_socket.onopen();

                player.onplay = function(){
                    if (locked) {
                        locked = false;
                        return true;
                    }

                    var message = {
                        method: "update",
                        paused: false,
                        current_time: player.currentTime
                    };

                    video_room_socket.send(JSON.stringify(message));
                    return true;
                };

                player.onpause = function(){
                    if (locked) {
                        locked = false;
                        return true;
                    }

                    var message = {
                        method: "update",
                        paused: true,
                        current_time: player.currentTime
                    };

                    video_room_socket.send(JSON.stringify(message));
                    return true;
                };

                player.onended = function(){
                    if (locked) {
                        locked = false;
                        return true;
                    }

                    player.currentTime = 0;
                    var message = {
                        method: "update",
                        paused: true,
                        current_time: 0
                    };

                    video_room_socket.send(JSON.stringify(message));
                };
            }, false);

            function onSelectedResult( event, ui ) {
                var message = {
                    method: "change",
                    id: ui.item.id
                };
                console.log('change video to ' + ui.item.id);
                video_room_socket.send(JSON.stringify(message));
            }

            $(function() {
              $("#header-search-term").autocomplete({
                source: "{% url 'search:api' %}",
                minLength: 1,
                autoFocus: true,
                appendTo: "#search-list",
                select: onSelectedResult,
              });
            });

        });

        $( document ).ready(function() {
            $("#header-search-term").attr("placeholder", "Change video...");
            $("#header-search-term").attr("aria-label", "Change video...");
        });

    </script>
    <script src="{% static 'video_room/js/player.js' %}"></script>
{% endblock %}