VinVC/VinVC/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('login.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^video/', include('video.urls')),
    url(r'^', include('video_room.urls')),

    url(r'^admin/', admin.site.urls),

    # Python Social Auth URLs
    url('', include('social.apps.django_app.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VinVC/login/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
]

VinVC/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [
    url(r'^(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^(?P<user_id>[0-9]+)/friends/$', views.friends, name='friends'),
    url(r'^(?P<user_id>[0-9]+)/uploaded/$', views.uploaded, name='uploaded'),
    url(r'^(?P<user_id>[0-9]+)/watched/$', views.watched, name='watched'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^requests/$', views.requests, name='requests'),
]

VinVC/login/models.py
from django.db import models

VinVC/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import get_user_model


def index(request):
    if request.user.is_authenticated:
        return redirect('video_room:feed')
    else:
        return render(request, "login/index.html")


@csrf_protect
def login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return redirect('video_room:feed')
    else:
        context = {'error_message': 'Wrong username or password'}
        return render(request, "login/index.html", context)


@csrf_protect
def signup(request):
    email = request.POST.get('email')
    password = request.POST.get('password')
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')

    try:
        validate_email(email)
    except ValidationError:
        context = {'error_message': 'The email address is not valid'}
        return render(request, "login/index.html", context)

    if all([first_name, last_name, email, password]):
        try:
            get_user_model().objects.create_user(email, email, password,
                                                 first_name=first_name,
                                                 last_name=last_name)
            user = authenticate(username=email, password=password)
            auth_login(request, user)
            return redirect('video_room:feed')
        except IntegrityError:
            context = {'error_message': 'Email is already in use'}
            return render(request, "login/index.html", context)
    else:
        context = {'error_message': 'A field is empty'}
        return render(request, "login/index.html", context)

VinVC/login/templates/login/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <title>Login in VinVC</title>
    <link rel="stylesheet" href="{% static 'login/css/login.css' %}" />
{% endblock head %}

{% block content %}
<video playsinline autoplay muted loop poster="{% static 'login/video/placeholder.jpg' %}" id="bgvid">
    <source src="{% static 'login/video/bg.mp4' %}" type="video/mp4">
</video>

<div id="content">
    <div id="login-text" class="visible-lg-block">
        <h1>
            <span id="typed-placeholder"><strong>VinVC</strong> is not</span>
            <span id="typed"></span>
        </h1>
    </div>
    <div id="login-form">
        <h3>Welcome to <a id="header-logo"></a></h3>

        <div class="social-buttons">
            <a class="btn btn-google" href="{% url "social:begin" 'google-oauth2' %}" role="button">
                <span class="fa fa-google"></span>Sign in with Google</a>
            <a class="btn btn-facebook" href="{% url "social:begin" 'facebook' %}" role="button">
                <span class="fa fa-facebook"></span>Sign in with Facebook</a>
        </div>

        <div class="strike-message"><span>or</span></div>

        <form class="register-form" action="{% url 'login:signup' %}" method="post">
            {% csrf_token %}
            <input type="text" name="first_name" required placeholder="First Name"/>
            <input type="text" name="last_name" required placeholder="Last Name"/>
            <input type="text" name="email" required placeholder="Email Address"/>
            <input type="password" name="password" required placeholder="Password"/>
            <button class="btn">Sign Up</button>
            <p class="message">Already registered? <a href="#">Sign In</a></p>
        </form>

        <form class="login-form" action="{% url 'login:login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username" required placeholder="Email or Username"/>
            <input type="password" name="password" required placeholder="Password"/>
            {% if error_message %}
                <p class="error-message">{{ error_message }}</p>
            {% endif %}
            <button class="btn">Log in</button>
            <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>
    </div>
</div>

<script src="{% static 'login/js/index.js' %}"></script>
<script src='{% static 'login/js/typed.js' %}'></script>
<script>
$(function() {
    $("#typed-placeholder").hide();
    $("#typed").typed({
        strings: ["Video Chat^800", "<strong>VinVC</strong> is not<br>&nbsp;Video Chat"],
        typeSpeed: 100
    });
});
</script>
{% endblock content %}